name: Windows
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Get all subsubmodules
      run: git submodule update --init --recursive
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build HookLib
      working-directory: ./OTC/libs/libs/HookLib/HookLib
      run: msbuild HookLib.vcxproj /p:Platform=Win32 /p:Configuration=Release /p:VisualStudioVersion=16.0
    - name: Build Zydis
      working-directory: ./OTC/libs/libs/Zydis/msvc/zydis
      run: msbuild Zydis.vcxproj /p:Platform=Win32 /p:Configuration="Release MT" /p:VisualStudioVersion=16.0
    - name: Prepare before compile OTC
      working-directory: ./OTC
      run: |
            mkdir libs/objects
            Copy-Item -Path .\libs\libs\HookLib\HookLib\Release\HookLib.lib -Destination .\libs\libs\HookLib.lib
            Copy-Item -Path .\libs\libs\HookLib\HookLib\Release\HookLib.pdb -Destination .\libs\libs\HookLib.pdb
            Copy-Item -Path .\libs\libs\HookLib\HookLib\Release\HookLib.obj -Destination .\libs\objects\HookLib.obj
            
            Copy-Item -Path .\libs\libs\Zydis\msvc\bin\ReleaseX86\Zydis.lib -Destination .\libs\libs\Zydis.lib
            Copy-Item -Path ".\libs\libs\Zydis\msvc\zydis\obj\Zydis-Win32-Release MT\Zydis.pdb" -Destination ".\libs\libs\Zydis.pdb"
      shell: pwsh
    - name: Build OTC
      working-directory: ./OTC
      run: msbuild OTC.vcxproj /p:Platform=Win32 /p:PreBuildEvent= /p:Configuration=Release /p:VisualStudioVersion=16.0
    - name: Move before upload
      working-directory: ./OTC/build
      run: |
            mkdir ready
            Move-Item -Path .\OTC.dll -Destination .\ready\OTC.dll
      shell: pwsh
    - name: SHA1 OTC
      working-directory: ./OTC/build/ready
      run: sha1sum OTC.dll > OTC.dll.sha1
    - uses: actions/upload-artifact@v1
      with:
        name: Release OTC
        path: ./OTC/build/ready
